### ISSUE TITLE
Using the same variable multiple times in the same expression gives unexpected result

### ISSUE THREAD

**Issue by megagrump** [irmen/prog8#101]
```
main {
	sub start() {
		uword a = 1
		uword b

		b = (a << 8) + (a << 6)
		txt.print_uw(b)
		txt.nl()

		a = (a << 8) + (a << 6)
		txt.print_uw(a)
	}
}
```
This prints
```
320
16448
```

I would expect `320` to be printed twice instead.

**Comment by irmen** [comment]
Me too.
I suspect this is a problem in the way the compiler tries to simplify such complex expressions by chopping them up into individual steps.... where it now first seems to do a=a<<8 and then a=a<<6 afterwards
