### ISSUE TITLE
Identifiers cannot start with an underscore

### ISSUE THREAD

**Issue by megagrump** [irmen/prog8#104]
I know this is a limitation inherited from 64tass. You get used to it. But sometimes I really want to start an identifier with an underscore and I find it annoying when I can't for no good reason.

Please consider this as a feature request 😄

**Comment by irmen** [comment]
Maybe this could be done with prefixing the symbols that start with an underscore.... 
Just like the compiler is already prefixing symbols with "p8p_" when they are 3 letters long to avoid confusing them with assembly instructions.

**Comment by megagrump** [comment]
Request withdrawn.
