### ISSUE TITLE
Don't do that!   [about the idea to remove drive num from diskio routines]

### ISSUE THREAD

**Issue by ssuukk** [irmen/prog8#106]
"get rid of the disknumber parameter everywhere in diskio, make it a configurable variable that defaults to 8. the large majority of users will only deal with a single disk drive so why not make it easier for them."

Probably the lamest idea I've seen today.

**Comment by irmen** [comment]
okay, well thanks for your feedback I guess.

Any reasoning behind your feelings?

**Comment by ssuukk** [comment]
If you don't find it awkward that procedure calls would depend on setting some variable instead of the normal way - by parameter to the procedure, then I can't really think about any other reason. Personally I use Ultimate 64 with two emulated drives (8,9), SD2IEC (10) and a meatloaf (which can be configured to be all remaining devices at once). The times of a single drive are long gone, anyway.

If you don't like supplying a parameter to I/O functions, why don't you implement default parameter values, instead? :D

**Comment by irmen** [comment]
default parameter values, interesting thought

**Comment by ssuukk** [comment]
Well, it would be definitely cleaner than depending on some semi-hidden state.

**Comment by irmen** [comment]
Semi-hidden but still documented and easily accessible. There are hundreds of such variables when programming on these systems, that are manipulated with various different subroutine calls that depend on each other. So it's not a weird choice.  

It would be nice if you had been a bit more considerate when formulating your initial comment, it's pretty unfriendly now.

**Comment by ssuukk** [comment]
It wasn't meant to be unfriendly, it was just spontaneous, honest reaction, like:

"I've seen you're moving windscreen wiper lever to the glove box in your next model, what a horrible idea!"

But then you explained:

"That's a harsh opinion, considering it is well documented in the Driver's Manual and easily accessible!".

And that changed my mind.

**Comment by irmen** [comment]
Discussed with others and conclusion is to go ahead with the change. Arugmentation is that there is enough internal state already going on when doing disk I/O so this matches the pattern people are used to already. And it simplifies the common case.
