### ISSUE TITLE
Array of Structs

### ISSUE THREAD

**Issue by mkaiserincomm** [irmen/prog8#107]
Why not arrays of structs?  Just define that they must be powers of 2 in size and the speed isn't that bad.  Structs must be 2, 4, 8, 16, 32,64,128 or 256 bytes long.   No other size allowed.  Round up and pad if they try.   Now math is easy.

**Comment by irmen** [comment]
because a compound type (struct) doesn't exist in prog8 at this time.
also structs of arrays are more efficient still on 6502.

**Comment by irmen** [comment]
I do think the padding to a power of 2 idea has some merit, but I don't see structs appear in the language any time soon, so I'll close this issue for now.
(the problem with padding is the potential of a LOT of wasted memory, which is a real issue on the tiny systems this language is meant for)

**Comment by irmen** [comment]
Interesting that you can do this with macros in assembler!   

> So more on topic, is there a way in prog8 for me to write my own libraries in either prog8 or assembly?  If so I can just put prog8 frontends on my already built libraries and call it a day.

Writing your own libraries in prog8 is trivial just write a module.p8 and put it somewhere in a directory that you then include with the -srcdirs command line option.  You can then simply import your own library modules from there in your programs.

Assembly much the same however you'll have to
- make sure it can be assembled by 64tass
- is inlined in a regular prog8 module with %asminclude.    It's not possible  to directly compile with "raw" .asm source files.   

Note that prog8 won't know about any symbols defined in the assembly source code as it just passes it to 64tass verbatim and doesn't attempt to parse it itself.
