### ISSUE TITLE
How to convert uword to str?

### ISSUE THREAD

**Issue by gerwazy102** [irmen/prog8#118]
Hello, I'm writing my own command for cx16shell which will uncompress Super Robin Hood picture packer graphics into nes chr format.

My question is: I pass filename as argument to the command. Pointer is stored at cx16.r2. So filename is for example "CHRSET.PP1" - now I want to add ".CHR" to this filename and save it to filesystem. I don't see any easy way to concatenate ".CHR" to cx16.r2 as it is `uword` and ".CHR" is `str`

I cannot find anything in docs about such usecase. Maybe I missed something. Could you please help me to solve this?

**Comment by gerwazy102** [comment]
I ended up with something like this but I feel there must be a better way.

```
        str fname = "                                 "
        ubyte i = 0
        repeat {
            fname[i] = @(cx16.r2 + i)
            if @(cx16.r2 + i) == 0 {
                break
            }
            i++
        }
        string.append(fname, ".CHR")
```

**Comment by irmen** [comment]
you can use `string.append` to concatenate two strings.

make sure the buffer you are appending text onto, is large enough to contain the resulting string! Otherwise you'll end up overwriting precious program data or code even

**Comment by gerwazy102** [comment]
I see, thank you very much for the detailed answer!
