### ISSUE TITLE
Docs: List all available @varflags/tags

### ISSUE THREAD

**Issue by adiee5** [irmen/prog8#120]
Documentation doesn't provide a convenient reference on all available @vartags, so it would be really nice if they would be listed like directives or datatypes.

**Comment by irmen** [comment]
https://prog8.readthedocs.io/en/latest/syntaxreference.html#variable-declarations  ?

**Comment by adiee5** [comment]
Hmm, ok

**Comment by irmen** [comment]
maybe putting them into a table makes it easier to read

**Comment by adiee5** [comment]
> maybe putting them into a table makes it easier to read

Yeah, it would
