### ISSUE TITLE
Fix definition of `cx16.fetch()` function

### ISSUE THREAD

**Issue by adiee5** [irmen/prog8#148]
The definition of fetch in cx16's syslib is incorrect:
https://github.com/irmen/prog8/blob/b70ce0015c6cca870cc0bdc425d6b31de358507f/compiler/res/prog8lib/cx16/syslib.p8#L398

this kernal function also takes `@A` as an address of the zeropage address, that holds the address. quoting docs:
> This function performs an `LDA (ZP),Y` from any RAM or ROM bank. The the zero page address containing the base address is **passed in .A**, the bank in .X and the offset from the vector in .Y.

**Comment by irmen** [comment]
what an awkward function to use

**Comment by adiee5** [comment]
🤷‍♂️

**Comment by adiee5** [comment]
> I guess stash() is also wrong? In the doc it says it doesn't pass the address in A but instead uses a fixed location somewhere else?

stash is correct, although prog8 doesn't have a definition of the memory location, which is specified somewhere in the docs
