### ISSUE TITLE
Confusing error when assigning illegal value in array 

### ISSUE THREAD

**Issue by cyborgar** [irmen/prog8#29]
Using somthing like this 
 `ubyte[] ar = [-2]`
gives 
 `error.p8:9:18: ERROR cannot type cast to string or array type`
which is a bit confusing since I assume it's assigning a byte to a ubyte arrray that fails. 

Note that I did have this somewhere like
 `ubyte[] ar = [ ..., CONST-2, ... ]`
which made a bit hard to figure out what was wrong.

**Comment by irmen** [comment]
thanks for reporting, i'll see if I can improve the error message !

**Comment by cyborgar** [comment]
Thanks.

Note that
`ubyte var = -1`
is legal (resulting in -1) so it's also a bit inconsistent. I'm not sure if it would have been better or worse to debug without the compile error :-)

**Comment by irmen** [comment]
huh? that should be a compilation error... -1 is a signed value and is not valid for ubyte type.  
Seems like the type checking / conversion got screwed up a little recently.
