### ISSUE TITLE
Add ASCII encoding for cx16's "ISO mode"?

### ISSUE THREAD

**Issue by meisl** [irmen/prog8#38]
### Rationale
Prog8 currently (v6.4) supports two character encodings: PETSCII (eg `"foo"`) and screencodes/pokes (eg `@"foo"`).
Now there's also [Commander X16's "ISO mode"](https://github.com/commanderx16/x16-docs/blob/master/Commander%20X16%20Programmer%27s%20Reference%20Guide.md#iso-mode).
However, there's no easy way in Prog8 to use strings or characters (literals) in this encoding.

### Proposal
Add some kind of support for switching to/from this and other encodings to the language.
The exact syntax, semantics and mechanism remain to be discussed.

### Workarounds
1. Use `\xHH` escapes inside strings, these are copied verbatim without translation.
   - Not really a lot of fun...
2. **Let [64tass](https://sourceforge.net/projects/tass64/)**, Prog8's assembler, **do the work**:
   - It has the directives `.enc`, `.cdef` and `.edef` which let you define a custom encoding
   - See example below for how to use them
3. Maybe others I don't know of.

### Discussion
* The technique outlined above and demonstrated below could also be employed by Prog8, even right now for the existing encodings, leading to code reduction
* Instead of emitting a bunch of hex literals to the `.asm` file - as is done atm - the literals from the p8 source could be pasted in there pretty much as-is
* "Pretty much" meaning: apart from the escape `\"` which would have to be replaced by eg `\{qq}` (see demo code)
* As for which **language constructs** to provide:
  - There's already the `@"string"` notation for screencodes/pokes - which is a bit unfortunate, as "@" probably rather hints to ASCII...
  - The "ISO mode" is only available on the X16, not the C64. So the compiler would allow the ISO/ASCII encoding only with `%target cx16`. Or maybe better not as restrictive, and just warn about it.
  - The `@` is also used for indicating where parameters go in asmsubs - something completely different.
  - A better (and more regular) way might be via
    * an `%option encoding_xyz`, setting the default for the whole src file (of course not imported ones)
	* and/or some modifier or built-in function to set the encoding for individual string literals (questionable)
	* in any case: the (syntactical) mechanism should be a) rather explicit (ie stating the actual *name* of the encoding), b) regular and c) extensible
	* none of the above three are met by the current `@` syntax, IMHO

Of course these are just a few thoughts of mine on the subject - looking forward to anybody else's :)

### Illustration
I've written a little demo, with explanations in comments. But first, here's how it looks like:
![prog8_issue38](https://user-images.githubusercontent.com/1493886/117735243-608eb080-b1f5-11eb-944e-15ee777c53e6.gif)

### Code
```
; x16emu -prg prog8_issue38.prg -run -gif prog8_issue38.gif,wait

%target cx16
%import textio ; txt.*
%import syslib ; cx16.*, sys.*
%zeropage basicsafe
%option no_sysinit

main {
	; Define the encoding at top of block
	; NOT inside a sub!
	%asm {{
			.enc	"ascii"		; define an encoding named ascii
			.cdef	" ~", 32	; identity for printable characters (from " " to "~")
			.edef	"\r", 13  	; define escape sequence for CR carriage return
			.edef	"\n", 13  	; define escape sequence for LF line feed, map it to CR (original: $0a)
			.edef   "\\", $5c	; define escape sequence for backslash (cannot be used in P8's PETSCII enc)
			.edef	"\t", [32, 32, 32, 32]	; TAB (original $09) -> four spaces
			.edef	"\{clr}", 147	; we can even define nice custom control sequences
			.edef	"\{qq}", $22	; or this: double quote (cannot define \")
	}}
	
	; String literals must also be defined via %asm; also in block
	%asm {{
		ascii_strings	.proc ; create a 64tass scope s.t. we can give them the same names as in p8
			.enc "ascii" ; not actually necessary since directly following the definition
		mytext
			.text "This is ASCII: lower & UPPER\nsecond\tline\twith\ttabs\r"
			.text "backslash in double quotes: \{qq}\\\{qq}"
			.byte 0 ; null-terminated for txt.print
			.pend
	}}
	
	; We can still use normal PETSCII by switching back via .enc "none":
	%asm {{
		petscii_strings	.proc
			.enc "none"
		myothertext
			.text "we are petscii (all upper case)"
			.byte 0 ; null-terminated for txt.print
			.pend
	}}
	
	
	; inline subs for convenient switching between modes
	inline sub iso_on() {
		txt.chrout($0f)
	}
	inline sub iso_off() {
		txt.chrout($8f)
	}
	
	sub start() {
		void cx16.screen_set_mode(0) ; switch to 40x30 text mode
		iso_on(); switch to ISO-8859-15 encoding ("ISO mode")
		
		; We cannot (yet?) use iso-/ascii-encoded literals in Prog8
		; because they're always a) translated and b) put "some place we don't know" (see issue #31)
		str garbled = "this is garbled: lower & UPPER\nsecond line\rdouble quote: \""
		txt.print(garbled)
		txt.nl()
		txt.nl()
		txt.nl()
		
		; Neither can we use escapes \\ (because there is no petscii equiv) nor \t (missing?)
		; ...not to speak of our custom ones like \{clr} (of course).
		; So each of the following would yield Prog8 syntax errors:
		;str backslash = "\\"
		;str tab = "\t"
		;str clr =  "\{clr}"

		; Workaround:
		;   1. put actual ASCII-encoded text in block (above) via %asm
		;   2. declare Prog8 uword to point to actual text
		;   3. with %asm: initialize the pointer accordingly
		; That's basically what the compiler would do as well.
		uword mytext
		%asm {{
			lda #<ascii_strings.mytext
			sta mytext
			lda #>ascii_strings.mytext
			sta mytext+1
		}}
		txt.print(mytext)
		txt.nl()
		txt.nl()
		txt.nl()
		
		uword myothertext
		%asm {{
			lda #<petscii_strings.myothertext
			sta myothertext
			lda #>petscii_strings.myothertext
			sta myothertext+1
		}}
		txt.print(myothertext)
		txt.nl()
		txt.nl()
		txt.nl()
		
		sys.wait(60) ; wait a second
		; make single screenshot
		%asm {{
			lda #1
			sta $9FB5
		}}
	}
}

```

**Comment by meisl** [comment]
:)

As an alternative for the `@` syntax, I was imagining ctrl sequences inside Prog8 strings (NOT in assembler):
 `"\{ascii}This is ASCII/ISO"`, `"\{petscii}we are petscii"`, `\{screencodes}what have you"`, ... 
Still possibly combined with an `%option encoding_xyz` or so for a per-file default.
* Pro
  - uniform and extensible
* Contra
  - maybe too "chatty", not so easily typed
  - puts a burden on the parser, since it's *inside* the string literals
  - btw: is an annotation needed only for literals, or for str vars in general? I'm not entirely sure...
  - what if user puts them *somewhere* in the string, not at the beginning?!

Then there's the question whether the `@` syntax can be dropped at all, or must be kept for backwards compatibility.

So maybe, as kind of a middle ground:
`@ascii"This is ASCII/ISO"` etc., and just `"using per-file-default encoding"` for, well, just that.
* Pro
  - extensible, but not as uniform if a single `@` is kept for backwards comp. (which it'd still allow)
  - easy extension to parser
  - cannot be put "somewhere strange" - simple and to-be-expected syntax error otherwise
* Contra
  - keeps the `@` character, which I, personally, don't really like there (not too big a deal though)
  - open question as above: annotation needed only for literals, or for str vars in general?

**Comment by irmen** [comment]
I'm no fan of adding magic control codes inside the string.  They won't work for character literals as well.
What do you mean with "annotation needed for str vars in general"? 

I was thinking of simply adding an 'i'  in front of the string that you want to be iso-encoded....   i"This is ISO!" but this introduces yet another prefix
or perhaps something piggybacking on the type-casting construct:   "This is ISO" as iso
however that poisons the grammar because string-encoding names are not data types.

**Comment by meisl** [comment]
Yes, pretty much d'accord. Ctrl codes are a bad idea, was rather to illustrate my train of thought.

> `i"This is ISO!"` but this introduces yet another prefix

Right, that's uniform in *some* way (also a one-character prefix as the current `@`), but not so as "i" relates well to "ISO" whereas "@" doesn't relate well to "pokes" or "screencodes". Also not extensible in the sense that you'd have to change the grammar for each new encoding. Not so with a common prefix - be it `@` or something else - followed by some name or shortcut, and then the actual literal. Of course, not so many more encodings are to be expected, it's more a matter of presentation to the programmer, of elegance if you will.

> ...`"This is ISO" as iso` ... however that poisons the grammar because string-encoding names are not data types.

That I wouldn't express as "poisons the grammar" but you're absolutely right in that they're not types like the others (eg not function types either). They are something else, "flavours" if you will. Note that I don't say "kinds"...

So yes: a clear "No" to `as iso`.

Maybe that's also the answer to my question/uncertainty re whether they are needed for literals only. I guess so, but I'm not sure. Another (probably mislead) way of thinking about the encoding is as some sort of modifier of the string type, similar to a parameterized type like `List<Integer>` in Java. But again, that really feels wrong, since such a type *argument* can only  be another regular type.

My question is this: can there ever be the need to associate a string *variable* with a specific encoding? I mean s.t. it makes proper sense. As said, I don't think so, but don't have it clear.

**Comment by meisl** [comment]
p.s.: One may well regard function types as of the same [kind](https://en.wikipedia.org/wiki/Kind_(type_theory)) as data types. Your use of the term "data type" seemed to be aimed as making a difference. Anyways, it's of no importance here.

**Comment by meisl** [comment]
Ah sorry, that's all way too theoretical. Let take a more practical approach:

What about the difference in "flavour" between these two: Pascal strings vs. C strings?

No I'm even more uncertain...

**Comment by meisl** [comment]
I should have been more clear:

Any representation of a string must somehow contain the *length* of that string. Now, there's the "Pascal way", prefixing it with a byte (or word, or...?) of memory containing that length - or the "C way", terminating it with a zero byte. Both have their pros and cons, but **both are workable ways of *encoding*** a string.

(I know that the "Pascal way" has been dropped from Prog8 time ago)

Anyhow, what I was trying to allude to: is this - and if so: how is it - essentially different from the question of how *characters* are encoded? Which aspect (or maybe both?) could/should be regarded as part of the *type*?
You see, at first glance one would naturally opt for "type" wrt Pascal vs C but not so wrt characters.

I think there isn't a definitive answer to that. Rather, it's a matter of choice - which in turn boils down to just taste, or, as a matter of fact, practicality / feasibility.
So, what to do about the ISO encoding? Well, I'm not sure, as said. But at least a bit more clear about what exactly I'm unsure of...


Btw.: fully and completely reflecting the (actual!) length of a string in its type leads to [Dependent Types](https://en.wikipedia.org/wiki/Dependent_type) (prime example: array bounds checking at *compile time*). That's of course a bit far-fetched for Prog8.

**Comment by irmen** [comment]
I like the idea of a "tag" for each string (and char) literal best.  This avoids messing with scope settings and allows for multiple different encodings in one scope, if you so desire.

I feel a prefix like this is the best:  ``encoding:"string"``  /  ``encoding:'c'`` so for example:  ``petscii:"hello"``, ``sc:"foo"``, ``iso:"François"``  and the default is defined by the target machine selected (always Petscii for now).

We'll keep ``@"screencode"`` as backwards compatibility for a few versions.

**Comment by irmen** [comment]
the change above implements the suggested encoding prefix syntax, and adds iso encoding.  However, it still does the encoding itself in the compiler, and doesn't use 64tass to define them.
