### ISSUE TITLE
Faulty codegen for memory access through non-zeropage ptr var

### ISSUE THREAD

**Issue by meisl** [irmen/prog8#42]
* **Prog8 version**: 6.4
* **Command line**: `java -jar prog8compiler-6.4-all.jar test.p8` or with `-noopt`
* **Source code**:
  Not so easily reproduced (see below), but here's the (a) problematic line:
  ```
	pokew(non_zp_ptr_var + CONST_OFFSET, some_value)
  ```
* **Expected:**
   Assembly code to be generated that
   - either first calculates `non_zp_ptr_var + CONST_OFFSET`, **stores the sum somewhere in zeropage**, eg `P8ZP_SCRATCH_W1` and then
      ```
          lda some_value
          ldy #0
          sta (P8ZP_SCRATCH_W1),y
          lda some_value+1
          iny
          sta (P8ZP_SCRATCH_W1),y
      ```
   - or - if `CONST_OFFSET` is small enough (ie. a byte) - **stores just `non_zp_ptr_var` in zeropage** (say, `P8ZP_SCRATCH_W1`), loads the `CONST_OFFSET` into `Y` and then
      ```
          lda some_value
          ldy #CONST_OFFSET
          sta (P8ZP_SCRATCH_W1),y
          lda some_value+1
          iny
          sta (P8ZP_SCRATCH_W1),y
      ```
* **Actual:**
  *ATTENTION: not always, only under certain conditions* - see below
  **`non_zp_ptr_var` is used directly**:
  ```
        lda some_value
        ldy  #CONST_OFFSET
        sta  (non_zp_ptr_var),y ; <<<<<<<<<
        lda some_value+1
        iny
        sta  (non_zp_ptr_var),y ; <<<<<<<<<
  ```
  Since this addressing mode, indirect zeropage indexed, can only be used with zeropage addresses, tass64 then complains:
  ```
  .\test.asm:4807:8: error: not a direct page address address '($1439),y'
        sta  (non_zp_ptr_var),y
              ^
  ```
* **Remarks**:
  - The actual source with which I encountered the problem consists of several p8 modules and is rather large, which seems to be part of the problem. I can't post it here in entirety.
  - I was able to hunt down the codegen for `pokew`, but that may well be just one instance.
  - Obviously, if `non_zp_ptr_var` actually *were* a zeropage var, then the actually generated code would be fine. So: one necessary condition is that the compiler runs out of zeropage locations to put local variables.
  - This allocation strategy is a thing of itself that could be improved. But first the compiler must be made to emit valid assembly even in this case.
  - A second condition seems to be that for some reason the compiler did not resort to first copying to `P8ZP_SCRATCH_W1` (or `P8ZP_SCRATCH_W2` which exists as well)
  - I have found that right before the problematic line there is another, similar one, which got translated correctly using `P8ZP_SCRATCH_W2`, as shown in "Expected". So my guess is that the compiler "thought" it ran out of scratches, so to speak.
  - There is a workaround for `pokew` - maybe not the only instance, as said - in Prog8, no asm:
    ```
        @(non_zp_ptr_var + CONST_OFFSET) = lsb(some_value)
        @(non_zp_ptr_var + CONST_OFFSET + 1) = msb(some_value)
    ```

**Comment by meisl** [comment]
I'll try to synthesize a (relatively) small p8 program that triggers it. I mean something that could be used in a test case.

**Comment by irmen** [comment]
maybe it helps to use %zeropage dontuse to trigger the issue?

**Comment by irmen** [comment]
@meisl before you spend too much time on this, I think this issue was already fixed in bf1b2066b6f36f9a8dff2315e61eb75acc4ec0a7

**Comment by irmen** [comment]
Closing this, because the bug was found in an outdated compiler version.

Feel free to re-open if the fix mentioned above doesn't address something you found.

**Comment by meisl** [comment]
@irmen thanks for looking into that, and yes, the mentioned commit seems to have fixed the issue. 
That is: me having had a quick look at the commit - without being into the code base (or even Kotlin, for the matter...) and without having tried out v7.0.

...which leads me to this: I cannot try v7.0 or the current master, because it's assuming release 39 of xemu16/the roms which isn't out (still). I'm sorry, but I can't afford to go into making my own. Ideally, there would've been a branch for that in prog8, and alongside the applicable/possible enhancements would've (also) committed to master. But of course I know that that's a bit of luxury, given the resources. Just so that you know; I'll just hope that r39 comes out officially soon, and we're all on the same page again, so to speak.

p.s.: i've been a bit busy with things, sorry for not having let heard of me for quite some time

**Comment by irmen** [comment]
Hey @meisl no worries thanks for writing back.
Yeah I expected the V39 official release (or at least, a beta of some sort that you can download) to be available by now, but work on the X16 kernal and emulator repos seem to have stalled again. I didn't anticipate that and assumed this period would be much shorter... hence no separate branch for the V39 modifications in the compiler.
That said, the modifications are mostly concerning the rom and ram banking and floating point routines. If you don't use both, it is likely your code compiled with the current prog8 beta version will work on a V38 emulator.

**Comment by meisl** [comment]
Confirmed:
1. `%zeropage dontuse` helps triggering it in 6.4
2. the attached example fails with 6.4 (as described) but not with 7.0-BETA2
3. most of my stuff so far also works with 7.0-BETA2, even with emu v38

Remark/questions:
* Rather quickly tested, not exhaustive
* The ram/rom bank thing that changes in v39 is just how (= where) you set them, right? So if I use `cx16.rambank(...)`/`cx16.rombank(...)` from [`compiler/res/prog8lib/cx16/syslib.p8`](../blob/19e99204b9629e3008fe5ae3ceb564bfd4b111ad/compiler/res/prog8lib/cx16/syslib.p8#L323) *and* I change (back) their implementation for v38 - then I should be fine?
* How do I compile using custom library files such as `syslib.p8`? That is: without building the whole compiler myself? I remember vaguely some `libDirs` option and/or env var...?
