### ISSUE TITLE
asmbinary import issue in windows?

### ISSUE THREAD

**Issue by cyborgar** [irmen/prog8#43]
I did write about my problems with %asmbinary in the X16 forum, but I actually did find a workaround for that part after thinking about the problem a bit more.

I added an small array in from of the import and can use that to figure out the start address of the actual data. Very hacky though.

However, the actual import by 64tass fails.

**%asmbinary "data.bin"**

then fails with 

**.\screen_test.asm:40:10: warning: the file's real name is not './data.bin' [-Wportable]
        .binary "./data.bin"
                ^**

Seem like 64tass doesn't like the ./ prefix for path. I can assemble this fine if I just remove this and run 64tass myself.

**Comment by irmen** [comment]
Not sure why I even bothered prefixing the path with ./
I've just pushed a potential fix for this. Can you test this yourself and see if the problem on Windows was resolved?  (I'm developing on Linux)

**Comment by cyborgar** [comment]
I have done a sort of half-hearted attempt to build myself. I.e. I've downloading the IntelliJ evaluation version and tested if I can get it to compile using that.  I have no experience with Kotlin (and not much with Java either to be honest).

I got stuck at 

D:\Dev\prog8\src\prog8-7.0-beta2\compilerAst\src\prog8\ast\antlr\Antr2Kotlin.kt:12:21
Kotlin: Unresolved reference: prog8Parse

I'm fine with just waiting for the next "official" bundle. I'm just testing out stuff I may have more use for later.

**Comment by irmen** [comment]
thanks for taking the time to try to compile it yourself. you shouldn't have to use intellij IDEA for this though, only the gradle build tool https://prog8.readthedocs.io/en/latest/building.html#building-compiler 

maybe I'll attach a prebuilt jar here later because to close this bug I'd really want to have it tested ok in the environment it occurs in (i.e. your windows setup)

**Comment by cyborgar** [comment]
Ok, that was a lot easier than I imagned. I was sort of dreading the IDE (Android Studio etc) route. I'm a unix guy myself and like using a plain text editor (Emacs) and the command line to do most work.

The asmbin include works fine now.

**Comment by irmen** [comment]
yeah the label scope issue I started working on and is unrelated.
