### ISSUE TITLE
Docs reference X16 v39 roms, but not available? 

### ISSUE THREAD

**Issue by mlongval** [irmen/prog8#44]
The docs for prog8 state that the system targets V39 of the Commander X16 ROMS. 
However the latest version available on the Commander X16 github is V38 (as of 11.06.2021) 
So far what I have compiled has worked on V38. 
The prog8 documentation as it stands seems a little confusing.

**Comment by irmen** [comment]
The official released version is V38 still, that is true. But the master branch of both the x16-rom and x16-emulator repositories contain what will become the V39 version of both, and you can build this version yourself or download a precompiled version that others provided elsewhere (f.ex. on the x16 forum).

It was expected that the official V39 release would have come out  by now already, but alas, it hasn't so far.

It's now taking a (too) long time for v39 to be released officially, I guess I can make the documentation discuss on this matter a little bit more detail.

**Comment by irmen** [comment]
Here you go 127c470746efbe3d0344b8c72d4e66f170f105a8
I hope this clears things up.

**Comment by mlongval** [comment]
Thanks yes it does. Cheers!
