### ISSUE TITLE
is -target on the command-line mandatory?

### ISSUE THREAD

**Issue by SplitSpine** [irmen/prog8#56]
Should this fail if you do NOT use -target cx16 ?

PS D:\CommanderX16\Prog8> & 'C:\Program Files\AdoptOpenJDK\jre-11.0.11.9-hotspot\bin\java.exe' -jar D:\CommanderX16\Prog8\prog8compiler-7.0-all.jar .\cx16\amiga.p8

Prog8 compiler v7.0 by Irmen de Jong (irmen@razorvine.net)
This software is licensed under the GNU GPL 3.0, see https://www.gnu.org/licenses/gpl.html

Compiler target: c64. Parsing...
importing 'amiga' (from 'cx16\amiga.p8')
importing 'textio' (library)
importing 'syslib' (library)
importing 'conv' (library)
←[91m[cx16\amiga.p8: line 3 col 1-16] Import: no module source file 'palette.p8' found  (I've looked in: embedded libs and [cx16, D:\CommanderX16\Prog8\prog8lib])

Works fine if I add -target cx16 to the command-line, but the source-code already have %target cx16 ?

PS it does this on the examples files for x16

**Comment by irmen** [comment]
Hi thanks for your interest in Prog8!
Yeah for now the command line switch is required to tell the compiler the machine target you intend to compile for.
The %target directive is (currently) only to tell the compiler what system the source file is compatible with. 

I'll think about it a bit, this behavior may change in the future.


By the way the reason it complains about a missing palette.p8 file is that this library does not exist for the default machine target (c-64)

**Comment by SplitSpine** [comment]
Thanks for the answer.

I just looked at the output and saw the line :"Compiler target: c64. Parsing..."
With the target cx16 it says: "Compiler target: cx16. Parsing..."

sooo.... I guess RTFM ? lol

**Comment by irmen** [comment]
@SplitSpine  btw, for upcoming 7.1 version of the compiler the %target directive in the program source code has been removed completely.
