### ISSUE TITLE
Extract data from variables

### ISSUE THREAD

**Issue by SplitSpine** [irmen/prog8#57]
In Millfork you can extract the data from variables like this:

**code_start
word mydata = 258 ; that would be $0102 in hex.
byte look_lo = mydata.b0
byte look_hi = mydata.b1
**code_end

look_lo whould have the value 2
look_hi whould have 1

Is there a way to do that in Prog8?

**Comment by meisl** [comment]
Yes, with built-in functions `lsb` and `msb`:
```
byte look_lo = lsb(mydata)
byte look_hi = msb(mydata)
```

**Comment by irmen** [comment]
That is the correct answer!
Note also that there is the reverse builtin-function ``mkword`` to create a new word value from separate msb and lsb bytes:
``uword w = mkword(msb, lsb)``

(closing this issue now as I think the original question was answered)
