### ISSUE TITLE
Empty subroutine is removed in optimization phase even if it's referenced

### ISSUE THREAD

**Issue by akumanatt** [irmen/prog8#67]
The following code crashes the compiler with null pointer exception:
```
main {
    sub start() {
        cx16.set_irq(&irq, false)
    }

    sub irq() {
    }
}
```

**Comment by irmen** [comment]
While the compiler crash is now fixed in the upcoming version, there's another problem with the code above:
the code generator doesn't yet properly emit a RTS for the empty irq() subroutine.

**Comment by irmen** [comment]
That got fixed now as well.
