### ISSUE TITLE
implement -D option as 64tass

### ISSUE THREAD

**Issue by ClaudioDaffra** [irmen/prog8#75]
as far as the 64tass assembler is concerned, the -D option is present
which allows you to pass values ​​to symbols. This is useful to me
to calculate some tables in order to speed up execution

is it possible to implement the -D option to the prog8 compiler?

below i found a workaround before importing the library

    main {
     
        ; define
     
        %asm {{
            xxx  = $E000
        }}  
        
        %import library
        
            source library  :
            
            ; if not def
            
            %asm {{
                .weak
                xxx  = $2000        
                
                ;default value if the one above does not exists
                
                .endweak
            }}    
        
    }

**Comment by irmen** [comment]
You mean that for instance,   ``p8compile -D SYMBOLNAME=99 blah.ph``  would put   ``SYMBOLNAME=99`` in the generated .asm before it's passed to the assembler?

That shouldn't be hard to add.

**Comment by ClaudioDaffra** [comment]
Yes, useful for different scopes, debug, symbols and conditional compilation and so on.

**Comment by irmen** [comment]
hmm Yeah, conditional assembly ony then because Prog8 itself doesn't have a source code preprocessor or metaprogramming to have conditional compilation of actual prog8 code.

**Comment by irmen** [comment]
Master branch now contains new -D SYMBOLNAME=VALUE command line option, if you want to try it out. Please let me know how it goes.

**Comment by irmen** [comment]
Great! Closing this issue then.
