### ISSUE TITLE
Shifting a ubyte more than 7 bits silently optimizes to a no op in non-simple cases

### ISSUE THREAD

**Issue by reltham** [irmen/prog8#83]
e.g.
ubyte byteValue = 2
uword wordValue = (byteValue << 11) | (byteValue >> 1)

wordValue will be set to just (byteValue >> 1) and drop the (byteValue << 11) part.
It does this silently.

Simpler cases work though:
ubyte byteValue = 2
uword wordValue = (byteValue << 11) 

wordValue in this case will be the correct result

**Comment by irmen** [comment]
For consistency with other calculations, a bit shift outside a byte size will no longer be auto promoted to a word.
Additionally, you *will* get a warning that the shift is too large and always results in zero.
