### ISSUE TITLE
Function calls in expressions may trash evaluator state

### ISSUE THREAD

**Issue by markjreed** [irmen/prog8#89]
Demonstration of the problem:

```
%import textio
%zeropage basicsafe
main {
  bool[1] expected = [ true ]

  sub get() -> bool {
    txt.print("get()")
    return expected[0]
  }

  sub start() {
    txt.color(12)
    txt.print("get() == expected: ")
    if get() == expected[0] {
      txt.color(5)
      txt.print("ok")
    } else {
      txt.color(2)
      txt.print("not ok")
    }
    txt.nl()
    txt.color(12)
    txt.print("expected == get(): ")
    if expected[0] == get() {
      txt.color(5)
      txt.print("ok")
    } else {
      txt.color(2)
      txt.print("not ok")
    }
    txt.nl()
  }
}

```

With the function call on the left of the equality operator, the test fails; with the function call on the right, it succeeds. Using a scalar instead of an array for the expected value avoids tickling the bug, as does eliminating the call to `txt.print()` in this simple example. But I have triggered it with more significant functions that don't do any printing; anything that winds up clobbering P8ZP_SCRATCH_B1 will do it.

**Comment by irmen** [comment]
Expression eval code seems to assume P8ZP_SCRATCH_B1 is not overwritten. Probably also problematic for the other scratch variables...

**Comment by irmen** [comment]
The IR/VM codegen doesn't suffer from this problem by the way.
