### ISSUE TITLE
Identical consecutive writes (wrongly) removed by compiler

### ISSUE THREAD

**Issue by megagrump** [irmen/prog8#91]
Having several identical assignments is not unusual with CX16 VERA's autoincrement, but the prog8 compiler removes them:
```
cx16.vaddr(1, $fc00, 0, 1) ; autoincrement 1
cx16.VERA_DATA0 = 0
cx16.VERA_DATA0 = 0 ; removed by compiler
cx16.VERA_DATA0 = 0 ; removed by compiler
...
```

**Comment by irmen** [comment]
Big oops! 
Weird though, I would have thought I made writes to the I/O and Vera register area special and they should be detected as such to not be removed...

I'll have a look at this. In the meantime you should probably use a piece of inline asm instead

```
stz cx16.VERA_DATA0
stz cx16.VERA_DATA0
stz cx16.VERA_DATA0
```

**Comment by megagrump** [comment]
I double checked and can I confirm it happens for me with the latest commits. I am a new user for 3 days or so and may have missed something.

Let me know if you require repro code or other information.

**Comment by irmen** [comment]
The code you pasted in the first comment should be enough to diagnose, thanks.

**Comment by megagrump** [comment]
This is probably related:

```
uword temp = cx16.memory_decompress(data, target)
; important: do nothing with temp
```
The compiler fatally removes the `memory_decompress` call, but only warns about removing `temp`.

**Comment by irmen** [comment]
I think this is now solved on master branch. (both issues)

**Comment by megagrump** [comment]
I think so too. Thank you very much!
