### ISSUE TITLE
Is there a way to create a custom target without forking the compiler?

### ISSUE THREAD

**Issue by rubythulhu** [irmen/prog8#92]
I'm building [Ben Eater's 65c02 kit](https://eater.net/6502), and I'm planning on continuing to build out my own custom extensions and hardware once I'm done going through his tutorials. I also think it would be fun to write everything in both 6502 asm and a higher level language like this one, to help myself understand better.

My computer will be 100% custom, so it makes little sense to contribute an upstream "target" back to this repository, but prog8 seems cool to play with and i'd like to experiment with using it to build software for my one-of-a-kind computer. But it seems like I can only define a new target within the source code of the prog8 compiler itself, and my only documented option here is to maintain a private fork?

**Comment by irmen** [comment]
There is no way to do it differently right now, indeed. The definitions of the target machine are embedded into the code on several places and there is no mechanism to specify them externally.
So yeah a fork is your only option right now

**Comment by irmen** [comment]
If you want, study the porting guide https://prog8.readthedocs.io/en/latest/portingguide.html
to see what's involved into properly supporting a new compilation target.

But as said, I have no plans at the moment to make this externally configurable. Maybe in a future version.
